#!/bin/bash
[ -e /usr/local/share/chruby/chruby.sh ] && source /usr/local/share/chruby/chruby.sh \
  && chruby 2

[ -e /usr/local/share/chruby/auto.sh ] && source /usr/local/share/chruby/auto.sh

load_keychain() {
  /usr/bin/keychain \
    $HOME/.ssh/id_rsa \
    $HOME/.ssh/id_rsa2 \
    > /dev/null

  source $HOME/.keychain/$HOSTNAME-sh
}

export ARCHFLAGS="-arch x86_64"

alias rssh='rea-ec2-ssh'
alias jim-cpdev='rea-assuming -u jgaylard cpdev-Developer'
alias jim-cpdevAdmin='rea-assuming -u jgaylard cpdev-Administrator'
alias jim-cops='rea-assuming -u jgaylard COPS-dev-NormalUser'
alias jim-prod='rea-assuming -u jgaylard Shared-Prod-NormalUser'
alias jim-muppets='rea-assuming -u jgaylard Muppets-Dev-Role'
alias jim-gandalf='rea-assuming -u jgaylard Gandalf-Dev-Role'
alias jim-staging='rea-assuming -u jgaylard Shared-Staging-NormalUser'


# Get cukes and specs passing faster for cp-agentadmin and  cp-domain
# https://community.rea-group.com/docs/DOC-16002
export RUBY_GC_HEAP_INIT_SLOTS=500000
export RUBY_HEAP_SLOTS_INCREMENT=250000
export RUBY_HEAP_SLOTS_GROWTH_FACTOR=1
export RUBY_GC_MALLOC_LIMIT=50000000
export CP_DOMAIN_ENV=development
#export AA_ENVIRONMENT=development
#export CP_AUTH_SSO_ENV=development
#export SHARED_COMPONENTS_ENV=development

export AWS_DEFAULT_REGION=ap-southeast-2
export AWS_REGION=ap-southeast-2

export GOPATH=/home/vagrant/workspace/go
export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin
