#!/bin/bash
[ -e /usr/local/share/chruby/chruby.sh ] && source /usr/local/share/chruby/chruby.sh \
  && chruby ruby2.0.0-p353

[ -e /usr/local/share/chruby/auto.sh ] && source /usr/local/share/chruby/auto.sh
