#!/bin/bash
[ -e /usr/local/etc/bash_completion ] && source /etc/bash_completion

export ARCHFLAGS="-arch x86_64"

alias rssh='rea-ec2-ssh'

alias tmux='TERM=xterm-256color tmux -2'

# Get cukes and specs passing faster for cp-agentadmin and  cp-domain
# https://community.rea-group.com/docs/DOC-16002
export RUBY_HEAP_MIN_SLOTS=500000
export RUBY_HEAP_SLOTS_INCREMENT=250000
export RUBY_HEAP_SLOTS_GROWTH_FACTOR=1
export RUBY_GC_MALLOC_LIMIT=50000000
export CP_DOMAIN_ENV=development
#export AA_ENVIRONMENT=development
#export CP_AUTH_SSO_ENV=development
#export SHARED_COMPONENTS_ENV=development
ulimit -n 8192

export AWS_DEFAULT_REGION=ap-southeast-2
export AWS_REGION=ap-southeast-2
