#!/bin/bash
[ -e /usr/local/share/chruby/chruby.sh ] && source /usr/local/share/chruby/chruby.sh \
  && chruby ruby-2.0

[ -e /usr/local/share/chruby/auto.sh ] && source /usr/local/share/chruby/auto.sh

[ -e /usr/local/etc/bash_completion ] && source /usr/local/etc/bash_completion

[ -d ~/.bash_completion.d ] && for file in ~/.bash_completion.d/*; do source $file; done

export PATH=$PATH:/usr/local/share/npm/bin
# call 'gitx .' from any dir
export PATH=$PATH:/Applications/GitX.app/Contents/Resources

### START-Keychain ###
# Let  re-use ssh-agent and/or gpg-agent between logins
/usr/local/bin/keychain \
  $HOME/.ssh/id_rsa \
  $HOME/.ssh/id_rsa2 \
  > /dev/null

source $HOME/.keychain/$HOSTNAME-sh
source $HOME/.keychain/$HOSTNAME-sh-gpg
### End-Keychain ###

# added to fix outdated ssl certs causing rubygems error
# brew install openssl
# brew link openssl --force
# brew install curl-ca-bundle
#
# http://railsapps.github.io/openssl-certificate-verify-failed.html
#export SSL_CERT_FILE=/usr/local/opt/curl-ca-bundle/share/ca-bundle.crt
export ARCHFLAGS="-arch x86_64"

alias sed=gsed

alias rssh='rea-ec2-ssh'

alias tmux='TERM=xterm-256color tmux -2'

# Get cukes and specs passing faster for cp-agentadmin and  cp-domain
# https://community.rea-group.com/docs/DOC-16002
export RUBY_HEAP_MIN_SLOTS=500000
export RUBY_HEAP_SLOTS_INCREMENT=250000
export RUBY_HEAP_SLOTS_GROWTH_FACTOR=1
export RUBY_GC_MALLOC_LIMIT=50000000
export CP_DOMAIN_ENV=development
#export AA_ENVIRONMENT=development
#export CP_AUTH_SSO_ENV=development
#export SHARED_COMPONENTS_ENV=development
ulimit -n 8192

# connect docker client to VM
export DOCKER_HOST=tcp://192.168.59.103:2375
export AWS_DEFAULT_REGION=ap-southeast-2
export AWS_REGION=ap-southeast-2
