#!/bin/bash
source /usr/local/share/chruby/chruby.sh
source /usr/local/share/chruby/auto.sh

source /usr/local/lib/python2.7/site-packages/powerline/bindings/bash/powerline.sh
export PATH=$PATH:/usr/local/share/npm/bin
# call 'gitx .' from any dir
export PATH=$PATH:/Applications/GitX.app/Contents/Resources
chruby ruby-2.0

### START-Keychain ###
# Let  re-use ssh-agent and/or gpg-agent between logins
/usr/local/bin/keychain \
  $HOME/.ssh/id_rsa \
  $HOME/.ssh/id_rsa2 \
  $HOME/.ssh/id_rsa_minthome \
  $HOME/.ssh/utah-corp-ap-southeast-2.pem \
  > /dev/null

source $HOME/.keychain/$HOSTNAME-sh
source $HOME/.keychain/$HOSTNAME-sh-gpg
### End-Keychain ###

# added to fix outdated ssl certs causing rubygems error
# brew install openssl
# brew link openssl --force
# brew install curl-ca-bundle
#
# http://railsapps.github.io/openssl-certificate-verify-failed.html
export SSL_CERT_FILE=/usr/local/opt/curl-ca-bundle/share/ca-bundle.crt
export ARCHFLAGS="-arch x86_64"

alias sed=gsed

alias updatedb='sudo /usr/libexec/locate.updatedb'

alias rssh='rea-ec2-ssh'

# Get cukes and specs passing faster for cp-agentadmin and  cp-domain
# https://community.rea-group.com/docs/DOC-16002
export RUBY_HEAP_MIN_SLOTS=500000
export RUBY_HEAP_SLOTS_INCREMENT=250000
export RUBY_HEAP_SLOTS_GROWTH_FACTOR=1
export RUBY_GC_MALLOC_LIMIT=50000000
export CP_DOMAIN_ENV=development
#export AA_ENVIRONMENT=development
#export CP_AUTH_SSO_ENV=development
#export SHARED_COMPONENTS_ENV=development
ulimit -n 8192
