#!/bin/bash
source /usr/local/share/chruby/chruby.sh
source /usr/local/share/chruby/auto.sh

. /Users/jimg/Library/Python/2.7/lib/python/site-packages/powerline/bindings/bash/powerline.sh

PATH=$PATH:/Users/jimg/Library/Python/2.7/bin
chruby ruby-1.9.3-p484
