#!/bin/bash
[ -e /usr/local/share/chruby/chruby.sh ] && source /usr/local/share/chruby/chruby.sh \
  && chruby ruby-2.0

[ -e /usr/local/share/chruby/auto.sh ] && source /usr/local/share/chruby/auto.sh

[ -e /usr/local/etc/bash_completion ] && source /usr/local/etc/bash_completion

PATH=$PATH:/usr/local/go/bin
export GOPATH=/home/vagrant/workspace/golang
