#!/bin/bash
[ -e /usr/local/etc/bash_completion ] && source /etc/bash_completion

[ -e /usr/local/share/chruby/chruby.sh ] && source /usr/local/share/chruby/chruby.sh \
  && chruby 2

[ -e /usr/local/share/chruby/auto.sh ] && source /usr/local/share/chruby/auto.sh

export PATH=$PATH:/usr/local/go/bin

load_keychain() {
  /usr/bin/keychain \
    $HOME/.ssh/id_rsa \
    > /dev/null

  source $HOME/.keychain/$HOSTNAME-sh
}

export ARCHFLAGS="-arch x86_64"
export GOPATH=/home/vagrant/workspace/golang
export PATH=$PATH:$GOPATH/bin

alias tmux='TERM=xterm-256color tmux -2'

