#!/bin/bash
[ -e /usr/local/etc/bash_completion ] && source /etc/bash_completion

load_keychain() {
  /usr/bin/keychain \
    $HOME/.ssh/id_rsa \
    > /dev/null

  source $HOME/.keychain/$HOSTNAME-sh
}

export ARCHFLAGS="-arch x86_64"

alias tmux='TERM=xterm-256color tmux -2'

